name: test-release

on: [push]

jobs:
  # tox-tests:
  # uses: ./.github/workflows/tox-tests.yml

  code-quality-release-pypi:
    # needs: tox-tests
    uses: ./.github/workflows/quality-and-send-to-pypi.yml
